# Generated by Django 4.2.11 on 2026-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='val_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
